{{- if .Values.secret.generate}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "nacos.labels" . | nindent 4 }}
data:
  authToken: {{ .Values.nacos.authToken | default (randAscii 64) | b64enc | b64enc}}
  identityKey: {{ .Values.nacos.identityKey | default (randAscii 12) | b64enc }}
  identityValue: {{ .Values.nacos.identityValue | default (randAscii 12) | b64enc }}
{{- end }}
